version: '3.7'
services: 

  gateway: 
    build: ./
    restart: always
    # volumes: 
    #   - './gracialab-api-gateway/src:/usr/gracialab-api-gateway'
    ports: 
      - '3000:3000'
    env_file:
      - .env
    environment: 
      - SERVER_PORT=3000
  
  auth: 
    build: ./../gracialab-auth-service/
    restart: always
    # volumes: 
    #   - './../gracialab-auth-service/scr:/usr/src/app/'
    ports: 
      - '5000:5000'
    env_file:
      - ./../gracialab-auth-service/.env
    environment: 
      - SERVER_PORT=5000
  
  # db:
  #   image: mongo
  #   container_name: db
  #   env_file:
  #     - ./env_var.env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=merqueo
  #     - MONGO_INITDB_ROOT_PASSWORD=merqueo3210
  #   volumes:  
  #     - dbdata:/data/db
  #   ports:
  #     - "27017:27017"

  # db:
  #   image: postgres
  #   # environment:
  #   env_file:
  #     - env_var.env
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  
volumes:
  dbdata:
  node_modules:
